version: '3'

services:
  web:
    build: .
    container_name: web
    command: >
      bash -c "sleep 5 &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000" 
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

  redis:
    image: "redis:alpine"
    container_name: redis
    restart: always

  celery:
    build: .
    container_name: celery
    command: bash -c "sleep 5 && python -m celery -A app worker -l info"
    env_file:
      - .env
    depends_on:
      - web
      - redis

volumes:
  postgres-data: